Onboarding screen
abdikaimovn/KirisShygysApp pull request #1
Opened 2024-01-22 18:38 UTC by abdikaimovn

2024-01-23 04:31 UTC, abdikaimovn commented
Забыл установить final у OnboardingViewController

2024-01-23 12:29 UTC, ZhassulanAimukhambetov requested changes

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on .DS_Store
Вот этого быть не должно

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore.xcodeproj/project.xcworkspace/contents.xcworkspacedata
вот это тоже можно в gitignor закинуть

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/.DS_Store
Вот это тоже надо почистить

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingCollectionCell.swift
> +class OnboardingCollectionCell: UICollectionViewCell {
final

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingCollectionCell.swift
> +        var title = UILabel()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingCollectionCell.swift
> +        var imgView = UIImageView()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingCollectionCell.swift
> +        var label = UILabel()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingCollectionCell.swift
> +        self.imageView.image = onboardingModel.image
self лишний и ниже везде

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var layout = UICollectionViewFlowLayout()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +    private lazy var sliderCollView: UICollectionView = {
sliderCollectionView

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var cView = UICollectionView(frame: .zero, collectionViewLayout: layout)
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var cView = UICollectionView(frame: .zero, collectionViewLayout: layout)
collectionView

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        cView.dataSource = self
лучше задать в методе setupCollectionView
а саму переменную сделать не lazy

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var pageControl = UIPageControl()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var button = UIButton()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var button = UIButton()
let

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "OnboardingCollectionCell", for: indexPath) as! OnboardingCollectionCell
никаких force unwrap

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +                        image: UIImage(named: "onbng1")!),
никаких force unwrap

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +                        image: UIImage(named: "onbng2")!)
никаких force unwrap

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +    static var shared = UIColor()
вот это зачем?

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +        }
UIColor(hex: "#E94D58") ?? .red

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +        }
UIColor(hex: "#C7B08E") ?? .brown

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +        }
UIColor(hex: "#2BA478") ?? .green

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +        }
`UIColor(hex: "#f9f9f9") ?? .lightGray`

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +    var grayColor: UIColor {
```
    var grayColor: UIColor {
        UIColor(hex: "#e0e0e0") ?? .gray
    }
```

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIColor+Extension.swift
> +    var lightBrownColor: UIColor {
и здесь также

2024-01-23 12:29 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIFont+Extension.swift
> +extension UIFont {
вместо этих 4-х методов можно использовать один, задать enum со стилями.
эти стили назвать, и метод должен принимать стиль, и возвращать font

2024-01-23 14:14 UTC, abdikaimovn commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        var button = UIButton()
У него target внутри добавляется

2024-01-24 08:14 UTC, ZhassulanAimukhambetov requested changes

2024-01-24 08:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/OnboardingModule/View/OnboardingViewController.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: OnboardingCollectionCell.typeName, for: indexPath) as! OnboardingCollectionCell
as! не убрал

2024-01-24 08:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/UIFont+Extension.swift
> +enum FontStyle {
мы не остановились на версии со структурой?

2024-01-24 11:02 UTC, merged