HomeModule + TransactionModule
abdikaimovn/KirisShygysApp pull request #10
Opened 2024-02-13 13:46 UTC by abdikaimovn

2024-02-13 16:05 UTC, ZhassulanAimukhambetov requested changes

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/AppConfiguration/SceneDelegate.swift
> +            goToController(with: tabVC)
тут сразу делай 
`goToController(with: TabBarContoller())`

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/Presenter/HomePresenter.swift
> +protocol HomeViewProtocol: AnyObject {
нужен точно?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/Presenter/HomePresenter.swift
> +final class HomePresenter {
и это)

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +    //Income view
и так понятно же по названию, зачем коммент)

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +    //Expense view
и тут также

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +    }()
очень много вьюшек, не думал создавать отдельные UIView?
тогда тут 3-4 вьюшки только создашь

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +
оставляй комменты
`// TODO: сделать то-то`

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +        }
однозначно надо контроллер разгрузить
Apple дает такую возможность и можно кастомные UIView создавать, раздели все на вьюшки

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +        10
это пока для тестов?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/HomeModule/View/TransactionTableViewCell.swift
> +        self.transName.text = transactionData.transactionName
вроде договорились же, что self лишний

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +
удаляй или оставляй коммент для чего он

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +
или подпиши сразу тут под протокол

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +
почему он class?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +
ответ "потому что TransactionServiceProtocol требует ссылочный тип"
тогда вопрос - почему TransactionServiceProtocol требует ссылочный тип? и для чего мы протокла подписываем под AnyObject, в каких случаях?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TabBarModule/TabBarContoller.swift
>      //TODO: Добавить модуль добавления новых транзакций
коммент можно удлаить?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TabBarModule/TabBarContoller.swift
>      //TODO: - FIX
и этот?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TransactionModule/Model/TransactionModel.swift
> +    var id: String?
var должно быть? в структуре?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TransactionModule/Model/TransactionModel.swift
> +    var id: String?
и все поля ниже

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TransactionModule/Model/TransactionModel.swift
> +    var transactionDate: String
и здесь тоже, точно var везде и почему var?

2024-02-13 16:05 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TransactionModule/Model/TransactionModel.swift
> +    var transactionDate: String
попробуй создать такую структуру через let и поменять один из параметров:
```
let model = ValidatedTransactionModel(...)
model.id = "new value"
```
что будет в этом случае?

2024-02-14 09:11 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/Presenter/HomePresenter.swift
> +protocol HomeViewProtocol: AnyObject {
Я специально подготовил связки, потому что чтобы работал homeView нужен transactionModule, для добавлении транзакций, чтобы homeView извлекать существующие транзакции
Дополню в следующем PR

2024-02-14 09:11 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/Presenter/HomePresenter.swift
> +final class HomePresenter {
Я специально подготовил связки, потому что чтобы работал homeView нужен transactionModule, для добавлении транзакций, чтобы homeView извлекать существующие транзакции
Дополню в следующем PR

2024-02-14 09:12 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +    //Income view
IncomeView имеет несколько компонентов, поэтому думал будет удобно для чтения

2024-02-14 09:12 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +    //Expense view
ExpenseView имеет несколько компонентов, поэтому думал будет удобно для чтения

2024-02-14 09:15 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +
Ок

2024-02-14 09:15 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/View/HomeViewController.swift
> +        10
Да, mock data

2024-02-14 09:16 UTC, abdikaimovn commented on KirisShygysAppStore/HomeModule/View/TransactionTableViewCell.swift
> +        self.transName.text = transactionData.transactionName
Ошибся Сэнсей, исправлю)

2024-02-14 09:23 UTC, abdikaimovn commented on KirisShygysAppStore/AppConfiguration/SceneDelegate.swift
> +            goToController(with: tabVC)
Ок

2024-02-14 09:25 UTC, abdikaimovn commented on KirisShygysAppStore/Network/UserDataService.swift
> +
Потому что AnyObject используется для типов class?

2024-02-16 07:42 UTC, merged