Services module
abdikaimovn/KirisShygysApp pull request #13
Opened 2024-02-24 16:18 UTC by abdikaimovn

2024-02-24 17:48 UTC, ZhassulanAimukhambetov requested changes

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/AuthenticationService.swift
> +        do {
 тут лучше async/await использовать

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +                            error: nil,
почему не сделаешь их с дефолтными значениями, чтобы везде не писать nil-nil

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +                    var lastMonthTransactions = [ValidatedTransactionModel]()
через .map делай лучше

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/UserDataService.swift
> +                    var lastMonthTransactions = [ValidatedTransactionModel]()
а тут в твоем случае через filter

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ReportModule/Presenter/ReportPresenter.swift
> +        var maxExpenseTitle = "none_label".localized
вот так объявлять переменные var - это не есть хорошо

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ReportModule/Presenter/ReportPresenter.swift
> +        for transaction in data {
через map или reduce вытаскивать лучше, ты же на IT учишься,  покажи это))

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ReportModule/View/QuoteCollectionViewCell.swift
> +    private let quotes = [
подпиши что это мок данные
и лучше их отдельно держать где-то, view не должно об этом значть ничего, ты должен и пробрасиывать через сервис-презенте

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ReportModule/View/ReportViewController.swift
> +        self.navigationController?.navigationBar.topItem?.backBarButtonItem = backBarButtonItem
почему опять self появились?
ты копи-пастишь с chatGPT?

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ReportModule/View/ReportViewController.swift
> +        self.navigationController?.setNavigationBarHidden(false, animated: animated)
тут тоже

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ReportModule/View/StoryCollectionViewCell.swift
> +    func configure(reportModel: ReportModel) {
вынеси эту функцию выше под init

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/Presenter/ServicesPresenter.swift
> +                                error: nil,
вот тут опять...
по идее вообще можно стандартные ошибки создать, их же не так много, чем каждый раз так модели создавать.
создай их как static и пропиши.

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/Presenter/ServicesPresenter.swift
> +                                error: nil,
если они какие-то локальные, то создай их ниже в private extension-e
```
private extension NetworkErrorModel {
    static var emptyTransition: NetworkErrorModel {
        ....
    }
}
```

и использовать их тогда вот так:

```
if transactionsData.isEmpty {
    self?.view?.showFailure(.emptyTransition)
    return
}
```

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/Presenter/ServicesPresenter.swift
> +                            NetworkErrorModel(
они очень много места занимают, и не несут вообще никакой логики

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
> +                cell.configure(
`configure(with: ...)`

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
> +
что это такое?))

2024-02-24 17:48 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
> +
и тут

2024-02-25 14:08 UTC, abdikaimovn commented on KirisShygysAppStore/Network/AuthenticationService.swift
> +        do {
Тяжко учить щас, не исправил

2024-02-25 14:09 UTC, abdikaimovn commented on KirisShygysAppStore/Network/UserDataService.swift
> +                            error: nil,
исправил

2024-02-25 14:09 UTC, abdikaimovn commented on KirisShygysAppStore/Network/UserDataService.swift
> +                    var lastMonthTransactions = [ValidatedTransactionModel]()
Исправлено через filter

2024-02-25 14:09 UTC, abdikaimovn commented on KirisShygysAppStore/ReportModule/Presenter/ReportPresenter.swift
> +        var maxExpenseTitle = "none_label".localized
Исправил

2024-02-25 14:09 UTC, abdikaimovn commented on KirisShygysAppStore/ReportModule/Presenter/ReportPresenter.swift
> +        for transaction in data {
Исправил

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ReportModule/View/QuoteCollectionViewCell.swift
> +    private let quotes = [
Исправлено

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ReportModule/View/ReportViewController.swift
> +        self.navigationController?.navigationBar.topItem?.backBarButtonItem = backBarButtonItem
Нет, с прошлого проекта, не углядел

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ReportModule/View/ReportViewController.swift
> +        self.navigationController?.setNavigationBarHidden(false, animated: animated)
исправил

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ReportModule/View/StoryCollectionViewCell.swift
> +    func configure(reportModel: ReportModel) {
Сделано

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ServicesModule/Presenter/ServicesPresenter.swift
> +                                error: nil,
Исправил

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ServicesModule/Presenter/ServicesPresenter.swift
> +                            NetworkErrorModel(
Исправил

2024-02-25 14:12 UTC, abdikaimovn commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
> +                cell.configure(
Исправил

2024-02-25 14:13 UTC, abdikaimovn commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
> +
Добавил комент

2024-02-25 14:13 UTC, abdikaimovn commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
> +
Добавил комент

2024-02-25 16:28 UTC, merged