Добавил модуль Статистики
abdikaimovn/KirisShygysApp pull request #14
Opened 2024-02-27 11:54 UTC by abdikaimovn

2024-02-27 16:55 UTC, ZhassulanAimukhambetov requested changes

2024-02-27 16:55 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
>      //TODO: - Fix
осталось кажется

2024-02-27 16:55 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/StatisticsModule/Presenter/StatisticsPresenter.swift
> +            view?.updateView(with: .expenseColor)
если эти функции вместе идут, почему не объединить?

2024-02-27 16:55 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/StatisticsModule/Presenter/StatisticsPresenter.swift
> +    private func configureChartData(_ segmentedControlIndex: Int) {
вообще работу с chart вынес бы в отдельную сущность

2024-02-27 17:31 UTC, abdikaimovn commented on KirisShygysAppStore/ServicesModule/View/ServicesViewController.swift
>      //TODO: - Fix
Исправлю

2024-02-28 06:53 UTC, abdikaimovn commented on KirisShygysAppStore/StatisticsModule/Presenter/StatisticsPresenter.swift
> +            view?.updateView(with: .expenseColor)
исправил

2024-02-28 06:53 UTC, abdikaimovn commented on KirisShygysAppStore/StatisticsModule/Presenter/StatisticsPresenter.swift
> +    private func configureChartData(_ segmentedControlIndex: Int) {
исправил

2024-02-28 09:57 UTC, merged