Refactoring + TabBarModule
abdikaimovn/KirisShygysApp pull request #9
Opened 2024-02-03 10:48 UTC by abdikaimovn

* Добавил новую папку Extensions где лежат все расширения
* Исправил отмеченные ошибки из предыдущего MR
* Добавил TabBarModule

2024-02-04 18:14 UTC, ZhassulanAimukhambetov requested changes

2024-02-04 18:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/AppConfiguration/SceneDelegate.swift
> +        self.goToController(with: navController)
self лишний

2024-02-04 18:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Network/AuthenticationService.swift
> +        Auth.auth().signIn(withEmail: email, password: password) { [weak self] result, error in
тут он принимает String непоциональный?

2024-02-04 18:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/ExtendedTapAreaButton.swift
> +final class ExtendedTapAreaButton: UIButton {
сделай еще гибче этот класс, сейчас у тебя нет возможности менять 20-ку.

2024-02-04 18:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/Support/Extensions/UIImage+Extension.swift
> +        UIGraphicsBeginImageContextWithOptions(size, false, 0.0)
этот метод deprecated же, у тебя могут быть падения если  size придет { 0, 0}
можешь даже проверить, вызови эту функцию с размером 0.

2024-02-04 18:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TabBarModule/CustomTabBar.swift
> +        self.layer.insertSublayer(shapeLayer, at: 0)
каждый раз при draw будет создаваться новый layer и добавляться - это нормальная логика?

2024-02-04 18:14 UTC, ZhassulanAimukhambetov commented on KirisShygysAppStore/TabBarModule/CustomTabBar.swift
> +    private var shapeLayer: CAShapeLayer?
зачем хранить ссылку?

2024-02-05 06:21 UTC, abdikaimovn commented on KirisShygysAppStore/Network/AuthenticationService.swift
> +        Auth.auth().signIn(withEmail: email, password: password) { [weak self] result, error in
Да
<img width="620" alt="image" src="https://github.com/abdikaimovn/KirisShygysApp/assets/56686500/1fe16ba7-d68a-45e1-982b-a4e1cd4f3115">

2024-02-06 06:26 UTC, ZhassulanAimukhambetov approved these changes

2024-02-06 06:30 UTC, merged